version: "3.9"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    container_name: elasticsearch1
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=asdf
      - xpack.security.enabled=true
      - xpack.security.transport.ssl.enabled=false
      - ingest.geoip.downloader.enabled=false
      - xpack.security.http.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms2g -Xmx2g  # Set both minimum and maximum heap size to 2GB (adjust as neededi)    

    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elastic_net
    ulimits:
      memlock:
        soft: -1
        hard: -1

volumes:
  esdata:
    driver: local

networks:
  elastic_net:
    driver: bridge

